[package]
name = "code-projects"
version = "0.1.0"
edition = "2021"
metadata.workspace = true

[dependencies]
dirs = "5.0.1"
covey-plugin.workspace = true
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.133"
tokio = { version = "1.41.1", features = ["fs"] }
